In [1]:
import numpy as np

In [2]:
xsam = np.linspace(0. , 2. , 11)

In [3]:
ysam = np.array([1,1.125,1.039,0.6663,-0.0650,-1.131,-2.448,-3.821,-4.944,-5.425,-4.83]) #ysam은 a이다.

In [4]:
h = []

In [5]:
for i in range(10):
    h.append(np.subtract(xsam[i+1], xsam[i]))

In [6]:
h = np.array(h)

In [7]:
h

array([0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2])

In [8]:
alpha = [0.]

In [9]:
for i in range(10):
    alpha.append((3*(ysam[i+1]-ysam[i])/h[i]) - (3*(ysam[i] - ysam[i-1])/h[i-1]))

In [10]:
alpha = np.array(alpha)

In [11]:
l = [1.]
mu = [0.]
zeta = [0.]

In [12]:
for i in range(10):
    l.append(2*(xsam[i+1] - xsam[i-1]) - h[i-1]*mu[i-1])
    mu.append(h[i]/l[i])
    zeta.append((alpha[i] - h[i-1]*zeta[i-1])/l[i])

In [13]:
l.append(1.)
zeta.append(0.)
b = [0. for i in range(11)]
c = [0. for i in range(12)]
d = [0. for i in range(11)]

In [14]:
l = np.array(l)
mu = np.array(mu)
zeta = np.array(zeta)
b = np.array(b)
c = np.array(c)
d = np.array(d)

In [15]:
l

array([ 1.        , -3.6       ,  0.8       ,  0.76      ,  0.81111111,
        0.75      ,  0.74736842,  0.75068493,  0.74666667,  0.74647887,
        0.74671533,  1.        ])

In [16]:
for j in range(10,-1,-1):
    c[j] = zeta[j] - mu[j]*c[j+1]
    b[j] = (ysam[j+1] - ysam[j])/h[j] - h[j]*(c[j+1]+2*c[j])/3
    d[j] = (c[j+1] - c[j])/(3*h[j])

IndexError: index 11 is out of bounds for axis 0 with size 11

In [17]:
b

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
xsam

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [20]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [21]:
from scipy.linalg import hilbert

In [22]:
H = hilbert(10)
H

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
        0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ],
       [0.5       , 0.33333333, 0.25      , 0.2       , 0.16666667,
        0.14285714, 0.125     , 0.11111111, 0.1       , 0.09090909],
       [0.33333333, 0.25      , 0.2       , 0.16666667, 0.14285714,
        0.125     , 0.11111111, 0.1       , 0.09090909, 0.08333333],
       [0.25      , 0.2       , 0.16666667, 0.14285714, 0.125     ,
        0.11111111, 0.1       , 0.09090909, 0.08333333, 0.07692308],
       [0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
        0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ,
        0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667],
       [0.14285714, 0.125     , 0.11111111, 0.1       , 0.09090909,
        0.08333333, 0.07692308, 0.07142857, 0.06666667, 0.0625    ],
       [0.125     , 0.11111111, 0.1      